---
title: "complex"
author: "s"
date: "2024-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
tableC1= read.csv("~/Downloads/data(41).txt", sep = "\t")
tableC2= read.csv("~/Downloads/data(40).txt", sep = "\t")
tableC3= read.csv("~/Downloads/data(39).txt", sep = "\t")
tableC4= read.csv("~/Downloads/data(38).txt", sep = "\t")
```

```{r}
num_rows1 = nrow(tableC1)
num_rows2 = nrow(tableC2)
num_rows3 = nrow(tableC3)
num_rows4 = nrow(tableC4)

cat("The table C 1 has", num_rows1, "rows.\n")
cat("The table C 2 has", num_rows2, "rows.\n")
cat("The table C 3 has", num_rows3, "rows.\n")
cat("The table C 4 has", num_rows4, "rows.\n")
```

```{r}
last_rows1 = tail(tableC1, 1000000)
last_rows2 = tail(tableC2, 1000000)
last_rows3 = tail(tableC3, 1000000)
last_rows4 = tail(tableC4, 1000000)
```

```{r}
num_rows_last_1 = nrow(last_rows1)
num_rows_last_2 = nrow(last_rows2)
num_rows_last_3 = nrow(last_rows3)
num_rows_last_4 = nrow(last_rows4)

cat("The table 1 has", num_rows_last_1, "rows.\n")
cat("The table 2 has", num_rows_last_2, "rows.\n")
cat("The table 3 has", num_rows_last_3, "rows.\n")
cat("The table 4 has", num_rows_last_4, "rows.\n")
```

```{r}
all_last_rows <- rbind(last_rows1, last_rows2, last_rows3, last_rows4)


```

```{r}
num_all_last_rows = nrow(all_last_rows)
cat("The table 1 has", num_all_last_rows, "rows.\n")
```

```{r}
head(all_last_rows)
tail(all_last_rows)
```

```{r}
# Convert angles to complex numbers using Euler's formula
all_last_rows$angle <- sapply(all_last_rows$angle, function(x) exp(1i * x * 2))

# Print the first few rows to check the transformation
head(all_last_rows)
tail(all_last_rows)
```

```{r}
all_last_rows <- subset(all_last_rows, x >= -49 & x <= 49 & y >= 140 & y <= 199)



All_Avg_Angle <- all_last_rows %>%
    group_by(x, y) %>%
    summarise(avg_angle = mean(angle))




tail(All_Avg_Angle)

nrow(All_Avg_Angle)

```

```{r}
# Convert complex numbers back to angles in radians
All_Avg_Angle$avg_angle <- sapply(All_Avg_Angle$avg_angle, Arg)

# Print the first few rows to check the transformation
head(All_Avg_Angle)

```

```{r}
# Divide every entry in 'avg_angle' by 2
All_Avg_Angle$avg_angle <- All_Avg_Angle$avg_angle / 2

# Print the first few rows to check the transformation
head(All_Avg_Angle)
```

```{r}

All_Avg_Angle$avg_angle <- round(All_Avg_Angle$avg_angle,1)
All_Avg_Angle$x=round(All_Avg_Angle$x)
All_Avg_Angle$y=round(All_Avg_Angle$y)


```

```{r}
range(All_Avg_Angle$avg_angle)
All_Avg_Angle$color <- with(All_Avg_Angle, rgb((sin(2*pi*avg_angle)+1)/2, (cos(2*pi*avg_angle)+1)/2, (-sin(2*pi*avg_angle)+1)/2))
All_heatmap_plot <- ggplot(All_Avg_Angle, aes(x = x, y = y, fill = color)) +
    geom_tile() +
    scale_fill_identity() +
    theme_minimal() +
    labs(fill = "Color", x = "X coordinate [µm]", y = "Y coordinate [µm]", title = "Heatmap of average orientation angle at each (x, y) point in the chamber")   

 
# Print the plot

print(All_heatmap_plot) 

```

```{r}
head(All_Avg_Angle)
```

```{r}
all_last_rows$x=round(all_last_rows$x)
all_last_rows$y=round(all_last_rows$y)
all_last_rows$angle=round(all_last_rows$angle,1)
all_last_rows$length=round(all_last_rows$length,2)

all_rounded=all_last_rows

tail(all_rounded)
summary(all_rounded$angle)
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
all_rounded <- subset(all_rounded, x >= -49 & x <= 49 & y >= 140 & y <= 199)
```

```{r}
# Calculate the average Horizontality at each (x, y) point
mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

All_Avg_Angle <- all_rounded %>%
    group_by(x, y) %>%
    summarise(avg_angle = mode(angle))




tail(All_Avg_Angle)
summary(All_Avg_Angle$avg_angle)

nrow(All_Avg_Angle)

```

```{r}
All_Avg_Angle$color <- with(All_Avg_Angle, rgb((sin(2*pi*avg_angle)+1)/2, (cos(2*pi*avg_angle)+1)/2, (-sin(2*pi*avg_angle)+1)/2))


```

```{r}
head(All_Avg_Angle)
```

```{r}
All_heatmap_plot <- ggplot(All_Avg_Angle, aes(x = x, y = y, fill = color)) +
    geom_tile() +
    scale_fill_identity() +
    theme_minimal() +
    labs(fill = "Color", x = "X coordinate [µm]", y = "Y coordinate [µm]", title = "Heatmap of average orientation angle at each (x, y) point in the chamber")   


# Print the plot

print(All_heatmap_plot) 
```

```{r}
# Define the length of the line segments
length <- 0.5

#calculate the start points of the line segments

All_Avg_Angle$start_y <- All_Avg_Angle$y + length * -cos(All_Avg_Angle$avg_angle * pi )
All_Avg_Angle$start_x <- All_Avg_Angle$x + length * sin(All_Avg_Angle$avg_angle * pi )



# Calculate the end points of the line segments
All_Avg_Angle$end_y <- All_Avg_Angle$y + length * cos(All_Avg_Angle$avg_angle * pi )
All_Avg_Angle$end_x <- All_Avg_Angle$x + length * -sin(All_Avg_Angle$avg_angle * pi )



# Create the plot
# Create the plot
All_Avg_Angle_plot <- ggplot(All_Avg_Angle,
aes(x = start_x, y = start_y)) +  # Use start_x and start_y for the x and y aesthetics
    geom_segment(aes(xend = end_x, yend = end_y), color = "black") +
    theme_minimal() +
    labs(x = "X coordinate [µm]", y = "Y coordinate[mµ]", title = "Mode orientation angle at each (x, y) point in the chamber")

# Print the plot
print(All_Avg_Angle_plot)

All_Avg_Angle
```
